// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixNamespace
{
    internal sealed partial class Vsix
    {
        public const string Id = "Vsix.71548858-d2bf-48dd-922d-f00c57bec505";
        public const string Name = "Fix Russian C";
        public const string Description = @"Fix Russias letter C included in English word.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
