// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixNamespace
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsixString = "20c6536c-78f8-44ad-b6cc-51551baffc3f";
        public static Guid Vsix = new Guid(VsixString);

        public const string CmdSetString = "8b1dd456-2340-45be-8748-641e1ef88f73";
        public static Guid CmdSet = new Guid(CmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}