// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FixRussianC
{
    internal sealed partial class Vsix
    {
        public const string Id = "FixRussianC.7f3692ad-4245-49af-b31a-61ca805e5a0c";
        public const string Name = "Fix Russian C 2019";
        public const string Description = @"Fix Russian letter C included in an English word and a English letter C included in a Russian word.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
